Header header

LatitudeLongitudeAltitude lla

LatitudeLongitudeDepth lld

Quaternion quaternion

RollPitchYaw rpy

RollPitchYaw rpy_dot

RollPitchYaw rpy_dot_dot

NorthEastDown pn_wrt_home

NorthEastDown pn_dot

NorthEastDown pn_dot_dot

SurgeSwayHeave vb

SurgeSwayHeave vb_dot

SurgeSwayHeave wb

SurgeSwayHeave wb_dot

float64 depth_unconstrained
	
bool final_reference

LatitudeLongitudeAltitude lla_final

RollPitchYaw rpy_final