###################################################
#################### [ P D I ] ####################
###################################################

K_surge: [0.3, 0, 1.0]    
K_sway: [0, 0, 0]
K_heave: [0.8, 0, 2.0]
K_roll: [0, 0, 0]
K_pitch: [0.07, 0, 0.17]
K_heading: [0.07, 0, 0.17]

K_surge_rate: [0, 0, 0]
K_sway_rate: [8, 0, 18]
K_heave_rate: [0, 0, 0]
K_roll_rate: [0, 0, 0]
K_pitch_rate: [0, 0, 0]
K_heading_rate: [0, 0, 0]

###################################################
##### [ surge sway heave roll pitch heading ] #####
###################################################

windupMax: [1, 1, 0.5, 1, 1, 0.6]
windupMax_vel: [1, 1, 0.5, 1, 1, 0.6] 
saturation: [20.0, 20.0, 30.0, 5.0, 5.0, 10.0] 